### PR TITLE
add optional pageRange property

### PR DESCRIPTION
**Pull request by MarcChasse**

### CODE REVIEW

**Comment by buck1ey** [comment]
Learn Build status updates of commit _[322d72c](https://github.com/MarcChasse/ai-builder/commits/322d72c6435e213e391df1cc3c84914b447a7077)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[ai-builder-docs/predict-action-pwr-automate.md](https://github.com/MarcChasse/ai-builder/blob/patch-1/ai-builder-docs/predict-action-pwr-automate.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/fa9c831e-0da3-e9b8-2cc1-3ff8d5c7b79b/202212161532350965-78/BuildReport?accessString=af0cab3e26a49526e495394ecddc4e6e745292a23333afb1bffe1a3aa44fd495).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/fa9c831e-0da3-e9b8-2cc1-3ff8d5c7b79b?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Antrodfr** [comment]
Hi @MarcChasse,

Is there any reason why you want to introduce this change?  Does the initial code fail because this optional parameter is not present?

Thanks

**Comment by MarcChasse** [comment]
@Antrodfr, I want to add it just to document that it exists.
The Predict card and its Peek code seems to hint at the parameter being called **Pages**
Predict
Predict Peek Code

This is the only documentation I was able to find that references the Infer Request field but it makes no mention of Pages.
Since the optional parameter is part of the original Predict card and the schema for Infer Request is not easily discoverable I think it should be documented.
Dynamic Predict - Infer Request

Thanks,
Marc

**Comment by v-aangie** [comment]
@MarcChasse - Thanks for your feedback. We have updated the docs to fix information about the pageRange property, and the updated will be live today. Closing this issue.

**Pull request closed without merging**
